project_id = "zxsswxzpzjimrrpcrrto"

[functions.verify-payment]
verify_jwt = true

[functions.process-gift-fulfillment] 
verify_jwt = true

[functions.shopify-order]
verify_jwt = false

[functions.shopify-collections]
verify_jwt = false

[functions.shopify-webhook]
verify_jwt = false

[functions.test-stripe-secret]
verify_jwt = false

[functions.create-gift-payment]
verify_jwt = false